version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  server:
    image: server
    depends_on: 
      - mongodb
    ports: 
      - '80:80'
