stages:
  - test
  - code_quality
  - build_and_publish_artifacts
  - build_and_publish_docker_image

include:
  - template: Code-Quality.gitlab-ci.yml

test:
  image: node:alpine
  stage: test
  script:
    - cd cliente
    - npm install
    - npm run test
  only:
    - practica10

code_quality:
  stage: code_quality
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [gl-code-quality-report.json]
    expire_in: 2 week

build_and_publish_artifacts:
  image: node:alpine
  stage: build_and_publish_artifacts
  script:
    - cd builder
    - npm install
    - node index
  artifacts:
    paths: [builder/dist/cliente.zip]
    expire_in: 2 week
  only:
    - practica10

build_and_publish_docker_image:
  image: docker:stable
  stage: build_and_publish_docker_image
  services:
    - docker:18-dind
  script:
    - docker login -u dmomotic -p 00ad4da1-6e7f-483f-aac1-a8839346608d
    - cd cliente
    - docker build --pull -t dmomotic/practica10 .
    - docker push dmomotic/practica10
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  after_script:
    - docker logout
  only:
    - practica10